### ISSUE TITLE
miles-podcast-card: lag sub-komponent for player

### ISSUE THREAD

**Issue by OlavRossoy** [miles-no/miles_web_components#18]
Lag wrapper for audio player i miles-podcast-card

![Image](https://github.com/miles-no/miles_web_components/assets/23364255/03d795eb-3463-4717-ab17-77bfc65b8506)

**Comment by skaihigh** [comment]
Done 

https://github.com/miles-no/miles_web_components/tree/main/src/audioplayer
and
https://github.com/miles-no/miles_web_components/tree/main/src/podcast-card

<img width="1173" alt="Skjermbilde 2023-06-12 kl  10 32 03" src="https://github.com/miles-no/miles_web_components/assets/1298612/9a833521-de63-453d-a7dc-83224fbc4ab9">
